### ISSUE TITLE
Pagination via WillPaginate/Kaminari

### ISSUE THREAD

**Issue by letronje** [remiprev/her#132]
What would be a good way to achieve pagination with #index calls ?

I was thinking of sending pagination information from the server side under json key ":meta" ( or via http headers) . What would be the correct way to extend "Her" to return a will_paginate / kaminari compatible  collection for calls returning a list of objects with pagination info as meta ?

Something like :

User.where(....).paginate(:page => 1, :per_page => 100) returning a will_paginate or kaminari collection.

Is it possible to write a middleware to transform objects returned by a 'her' call ?

**Comment by 7h3kk1d** [comment]
I realize this is an old issue but is this supposed to allow you to iterate through the paginated collection transparently?

**Comment by 7h3kk1d** [comment]
I wrote a pager that I'm going to move into a mixin that allows me to handle my paginated resources. It requires a page scope on the model.
```diff
diff --git a/lib/her/model/relation.rb b/lib/her/model/relation.rb
index 2daa80b..0e9595d 100644
--- a/lib/her/model/relation.rb
+++ b/lib/her/model/relation.rb
@@ -73,6 +73,10 @@ module Her
         end
       end
 
+      def paged
+        Pager.new self
+      end
+
       # Fetch specific resource(s) by their ID
       #
       # @example
@@ -159,6 +163,31 @@ module Her
       def clear_fetch_cache!
         instance_variable_set(:@_fetch, nil)
       end
+
+
+      class Pager < Struct.new(:collection)
+        include Enumerable
+
+        def each
+          fetch(1) do |item|
+            yield item
+          end
+        end
+
+        private
+
+        def fetch(page_number, &block)
+          response = collection.page(page_number)
+
+          response.each do |item|
+            yield item
+          end
+
+          if response.count > 0
+            fetch(page_number + 1, &block)
+          end
+        end
+      end
     end
   end
 end
```
