### ISSUE TITLE
Dynamic collection_path

### ISSUE THREAD

**Issue by stevschmid** [remiprev/her#152]
Lets say I have an API which provides two resources: ``User`` and ``Comment``. The comments can accessed with or without a user.

```
/user/42/comments  -> Returns only comments from User with ID 42
/comments -> Returns all comments
```

Is there any way to consume such an API with her? ``collection_path`` doesn't support optional parameters.

**Comment by moofish32** [comment]
close this?

**Comment by stevschmid** [comment]
RIP in pepperonis her!

**Comment by masciugo** [comment]
how can you achieve this if User is not an her model but an activerecord?
