### ISSUE TITLE
Accessing deeply-nested singleton resource hits incorrect URL - what am I doing wrong?

### ISSUE THREAD

**Issue by edtjones** [remiprev/her#175]
Hi there,

I'm having some issues accessing a deeply-nested resource. The URL is in the format:

`/documents/1234/pages/5678/diff?old=1&new=2`

My Her models are as follows:

``` ruby
class Document
   include Her::Model
   has_many :pages
end
```

``` ruby
class Page
   include Her::Model
   has_one :diff
end
```

``` ruby
class Diff
   include Her::Model
end
```

The problem I'm having is that calling `.diff` on a page object hits a non-existent `/pages/5678/diff` endpoint instead of the correct `/documents/1234/pages/5678/diff` endpoint.

For example:

``` ruby
doc = Document.find(1234) #returns a Document object
page = doc.pages.find(5678) #returns a Page object
diff = page.diff.where(old: 1, new: 2) # incorrectly hits /pages/5678/diff
```

What am I doing wrong?

Thanks :-)

**Comment by oliverzeyen** [comment]
@Dakuan Any further explanation would be appreciated!

**Comment by edtjones** [comment]
hi @ddevaal @oliverzeyen the answer is that the actual json returned from the server needs to have a field referencing the parent ID. So in my document/pages/diff example above, data on /documents/1234/pages/5678 needs to include `document_id: 1234` in the json response.

There is another way to hit deeply nested resources, and it's cheaper than this way anyway. To use my example from above:
```
class Diff
   collection_path "/documents/:document_id/pages/:page_id/diff"
end
Diff.where(_document_id: 1234, _page_id: 5678).first #hits /documents/1234/pages/5678/diff without having to walk through the ancestor resources
```

Hope that's useful.
