### ISSUE TITLE
Restrict operations

### ISSUE THREAD

**Issue by jsmestad** [remiprev/her#18]
### What

Restrict a Her::Model to only supporting certain operations.
### Why

In the case where you want to use all the features of the Her ORM, but you only have read-only access to a given object.
### Proposed DSL

``` ruby
class Profile
   include Her::Model

   # Whitelist options
   supports :read, :create, :update, :delete

   # Blacklist actions
   restricts :update, :delete
end
```

I like the idea of whitelisting with an `:all` over blacklisting, thoughts?

**Comment by mustela** [comment]
:+1: to have feature

**Comment by giedriusr** [comment]
Nice idea.
