### ISSUE TITLE
Undefined Method '+' for nil:NilClass

### ISSUE THREAD

**Issue by d3vkit** [remiprev/her#19]
Hopefully this is not a stupid question, or something obvious, but I can't get Her to work at all. I've tried to follow the readme to the letter but I must be missing something.

Tried with ruby-1.8.7-p370, ree-1.8.7-2012.02, ruby-1.9.3-p194, same result each time.
Using rails 3.2.3

I have a model User in app2 which I want to pull from into app1.

```
# app1/Gemfile
gem 'her'

# app1/config/initializers/her.rb
# http://local.portal is app2, and I can access it fine through my browser

Her::API.setup :url => "http://local.portal" do |connection|
  connection.use Faraday::Request::UrlEncoded
  connection.use Her::Middleware::DefaultParseJSON
  connection.use Faraday::Adapter::NetHttp
end

# app1/models/user.rb
class User
  include Her::Model
end

# rails c
Loading development environment (Rails 3.2.3)
1.8.7-p370 :001 > u = User.all
NoMethodError: undefined method `+' for nil:NilClass
    from /home/tom/.rvm/rubies/ruby-1.8.7-p370/lib/ruby/1.8/net/http.rb:1118:in `addr_port'
    from /home/tom/.rvm/rubies/ruby-1.8.7-p370/lib/ruby/1.8/net/http.rb:1078:in `begin_transport'
    from /home/tom/.rvm/rubies/ruby-1.8.7-p370/lib/ruby/1.8/net/http.rb:1048:in `request'
    from /home/tom/.rvm/rubies/ruby-1.8.7-p370/lib/ruby/1.8/net/http.rb:1037:in `request'
    from /home/tom/.rvm/rubies/ruby-1.8.7-p370/lib/ruby/1.8/net/http.rb:543:in `start'
    from /home/tom/.rvm/rubies/ruby-1.8.7-p370/lib/ruby/1.8/net/http.rb:1035:in `request'
    from /home/tom/.rvm/rubies/ruby-1.8.7-p370/lib/ruby/1.8/net/http.rb:772:in `get'
    from /home/tom/.rvm/gems/ruby-1.8.7-p370@io/gems/faraday-0.7.6/lib/faraday/adapter/net_http.rb:59:in `call'
    from /home/tom/.rvm/gems/ruby-1.8.7-p370@io/gems/faraday-0.7.6/lib/faraday/request/url_encoded.rb:14:in `call'
    from /home/tom/.rvm/gems/ruby-1.8.7-p370@io/gems/faraday-0.7.6/lib/faraday/response.rb:8:in `call'
    from /home/tom/.rvm/gems/ruby-1.8.7-p370@io/gems/faraday-0.7.6/lib/faraday/connection.rb:210:in `run_request'
    from /home/tom/.rvm/gems/ruby-1.8.7-p370@io/gems/faraday-0.7.6/lib/faraday/connection.rb:93:in `get'
    from /home/tom/.rvm/gems/ruby-1.8.7-p370@io/gems/her-0.2/lib/her/api.rb:67:in `send'
    from /home/tom/.rvm/gems/ruby-1.8.7-p370@io/gems/her-0.2/lib/her/api.rb:67:in `request'
    from /home/tom/.rvm/gems/ruby-1.8.7-p370@io/gems/her-0.2/lib/her/model/http.rb:37:in `request'
    from /home/tom/.rvm/gems/ruby-1.8.7-p370@io/gems/her-0.2/lib/her/model/orm.rb:64:in `all'
    from (irb):11.8.7-p370 :002 > 
```

I've been working at this for a couple hours now, getting nowhere. I must be missing something very simple, but for the life of me can't see it. If you have any suggestions (or if this is actually a bug and I also missed THAT in the tickets), I am all ears.

Thanks, and I am really looking forward to using Her!

**Comment by zymtx5g79k** [comment]
The same error for faraday 0.9.1

vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'
vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
vendor/bundle/ruby/2.2.0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
vendor/bundle/ruby/2.2.0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/base.rb:187:in `call'
...
