### ISSUE TITLE
3 levels of nesting?

### ISSUE THREAD

**Issue by Dakuan** [remiprev/her#204]
Im having some issues getting nested resources to work.

The API I'm talking too looks like this:

```
get /menus/:menu_id
get /menus/:menu_id/sub_menus
get /menus/:menu_id/sub_menus/:sub_menu_id
get /menus/:menu_id/sub_menus/:sub_menu_id/sub_menu_items
get /menus/:menu_id/sub_menus/:sub_menu_id/sub_menu_items/:sub_menu_item_id
```

My models look like this:

``` ruby
class Menu
    include Her::Model
    has_many :sub_menus
end

class SubMenu
    include Her::Model
    has_many :sub_menu_items
    belongs_to :menu
end

class SubMenuItem
    include Her::Model
    belongs_to :sub_menu
end
```

The first levels of nesting work fine

```
Menu.find(1) 
=> #<Menu(menus/1) id=1 text="places to eat">
```

```
Menu.find(1).sub_menus.find(1)
 => #<SubMenu(sub_menus/1) id=1 text="greasy spoon"> 
```

However, with the final layer of nesting, it all goes wrong:

```
Menu.find(1).sub_menus.find(1).sub_menu_items.find(1)
Her::Errors::ParseError: Response from the API must behave like a Hash or an Array (last JSON response was "Cannot GET /sub_menus/1/sub_menu_items/1")
```

So it's looking for the wrong url:
`/sub_menus/1/sub_menu_items/1`
rather than:
`/menus/1/sub_menus/1/sub_menu_items/1`

Anything I do to fix this?

**Comment by oliverzeyen** [comment]
@Dakuan Sorry for opening an old issue but I'm having the exact same problem and don't really get how to solve this. Actually I'm not able to provide the parent_id because I can't even access it. Would you be so kind and give me a code example? Thank you so much. Olli
