### ISSUE TITLE
Assign Attributes not making attributes dirty

### ISSUE THREAD

**Issue by tdtadeu** [remiprev/her#251]
I have tried the following both on my code and on the rails console:

`user = User.find(client_id: 1)`
`=> #<User(/api/clients/1/users/1) name="John">`
`user.name = "Dan"`
`=> #<User(/api/clients/1/users/1) name="Dan">`
`user.name_changed?`
`=> true` Everything ok! :+1:

But then if I try:
`user = User.find(client_id: 1)`
`=> #<User(/api/clients/1/users/1) name="John">`
`user.assign_attributes {name: "Dan"}`
`=> #<User(/api/clients/1/users/1) name="Dan">`
`user.name_changed?`
`=> false` Uh-oh!

It seems the assign_attributes doesn't pass through the Dirty Attributes module, or something like that?

**Comment by paulvt** [comment]
This fix seems to work only partially for me, as it doesn't seem to check if you actually change the value (which also isn't tested by the test):

    prod = Product.find(1)
    => #<Product(/rest/products/1) name="Player">
    prod.name = "Player"
    => "Player"
    prod.changes
    => {"name"=>["Player", "Player"]}

**Comment by caomania** [comment]
@paulvt it's resolved by this pull request. https://github.com/remiprev/her/pull/314 Still waiting to hear back from @remiprev

**Comment by paulvt** [comment]
@caomania Great! Applied it locally for now :)
