### ISSUE TITLE
Best way to authenticate with HTTP Basic?

### ISSUE THREAD

**Issue by alainmeier** [remiprev/her#252]
Our authentication system works like Stripe's wherein the username field in HTTP Basic Auth has to be the user's API key. So I am trying to set this up with Her, but I can't seem to get it quite right. I created some middleware:

``` ruby
class ApiKeyAuthentication < Faraday::Middleware
  def call(env)
    username = Base64.encode64(RequestStore.store[:user_api_key])
    env[:request_headers]["Authorization"] = "Basic " + Base64.encode64(username + ":")
    @app.call(env)
  end
end
```

And I set the `RequestStore.store[:user_api_key]` in the ApplicationController. Then I included the middleware in the her config file. I cannot set the API key directly from the config file (like #50) because it has to be supplied by the ApplicationController. However, it appears that this does not authenticate properly. What is the best way to authenticate with HTTP Basic?

**Comment by zacharywelch** [comment]
README updated in #431
