### ISSUE TITLE
Fallback behavior for her models

### ISSUE THREAD

**Issue by hubert** [remiprev/her#254]
my company is using her in a number of places now to connect a bunch of our services. one of the things i've found myself wanting to have is to provide a way for services to fail gracefully in the event that the service calls fail. something like this:

```
class Foobar
  include Her::Model
end

Class FoobarsController
  def save
     if Foobar.new(baz: 'qux').save { false }
       redirect_to index_path
     else
       render 'new'
     end
   end
end
```

is this something you would consider a valuable addition to her? i have a basic implementation of this worked out if you're interested in discussing further.

**Comment by zacharywelch** [comment]
Going ahead and closing this one
