### ISSUE TITLE
Syntax error, unexpected & association.fetch.time=(*args, &block)

### ISSUE THREAD

**Issue by george-semenov** [remiprev/her#310]
Getting this error when trying to assign `time` attribute to the `has_one` association, e.g.,
`parent.has_one_assoc.time = x`. At `association_proxy.rb` Her tries to `module_eval` following code:

    def time=(*args, &block)
      association.fetch.time=(*args, &block)
    end

Version of Her is 0.7.2.

**Comment by hubert** [comment]
#282 merged
