### ISSUE TITLE
Web site needs reconfigured

### ISSUE THREAD

**Issue by andyw8** [remiprev/her#316]
http://her-rb.org/

> Site Disabled - Oh no! It looks like this Pages site has been disabled due to a misconfigured custom domain.

**Comment by giedriusr** [comment]
Indeed. Please have a look at it.

**Comment by mtwentyman** [comment]
Flagging @remiprev and @pencil to ensure they see this so they can turn it off and on again :)  Thanks guys!

**Comment by remiprev** [comment]
Fixed! `her-rb.org` now redirects to `www.her-rb.org` :smile:

**Comment by linkyndy** [comment]
Thank you! :+1:
