### ISSUE TITLE
Custom get/post for active record objects

### ISSUE THREAD

**Issue by giedriusr** [remiprev/her#327]
Do you ever needed to call `@model.custom_action` ? Because AR objects support restful methods, but no custom methods. Is this something I've missed or it's just doesn't exist yet?
I know about the possibility with `custom_get` and `custom_post`, but that's for collection. I need it for a specific record.

i.e.
`@model.custom_action` would trigger
`# http://www.endpoint.com/api/users/:id/custom_action`

Anyone?

Thanks

**Comment by giedriusr** [comment]
Such a great gem, sad to see it's inactiveness and lack of maintainers.

**Comment by mtwentyman** [comment]
It's in a transitional place; see #324

**Comment by giedriusr** [comment]
@mtwentyman I saw that post, but it's quite inactive. Hopefully `her` will find new home.

**Comment by tustar** [comment]
@giedriusr Try this.
```
custom_get :custom_action 
# key-value
User.custom_action(id: xxx) 
# json
User.custom_action({id: xxx})
```

**Comment by giedriusr** [comment]
@tustar thanks. I don't think you correctly understood the initial issue.
`@model.custom_action #(GET or POST)` is an instance not a class. I am aware that there is custom_get and custom_post, but it is valid only on class level, not an instance :/

**Comment by bf4** [comment]
@giedriusr maintainers are people with limited resources.  Moving on is fairly common. And @remiprev is being responsive, so I have no complaints.  

Have you tried `User.raw_get("api/users/:id/custom_action")` (or `raw_post`)? It just gives you a parsed request and response object back, but that's useful. and you can call it with a block.
If you wrap that in e.g. `def User.custom_action(id); raw_get("api/users/:id/custom_action"); end`.  (I assume you're not talking about specifying a nested route)

**Comment by giedriusr** [comment]
@bf4 I am not complaining either :-) I agree that things change and life goes on.
