### ISSUE TITLE
create! does not exists, able to save with failing validations

### ISSUE THREAD

**Issue by reneweteling** [remiprev/her#339]
Hey there,

Ive got a question. Why does Model.create! doesnt exist, its very handy to know when something breaks. Also why have you guys chose to be able to persist data that fails validation?

Now instead of 
```ruby
Model.create!( name: 'Rene' )
```

i have to write
```ruby
model = Model.new( name: 'Rene' )
if model.valid?
   model.save
else
   puts "\n\n\nERROR!!!!\n#{answer.errors.full_messages.to_sentence}\n\n\n\n"  
end
```

this is pasted from your doc, just to illustrate your discussion 
```ruby
class User
  include Her::Model

  attributes :fullname, :email
  validates :fullname, presence: true
  validates :email, presence: true
end

@user = User.new(fullname: "Tobias Fünke")
@user.valid? # => false

@user.save
# POST "/users" with `fullname=Tobias+Fünke` will still be called, even if the user is not valid
```

<3 for the gem btw!!

**Comment by emilebosch** [comment]
My .2c.
- I suggest methods with a bang (!) should raise when validation fails
- Invalid models shouldn't post but return false.

**Comment by hubert** [comment]
@reneweteling in my mind there are two separate issues here.

1) allowing the request to continue when client side validation fails. not sure what the original thought was on this, but i don't see an advantage to it.
2) the existence of bang methods. these should be pretty straightforward to add in most cases.

i am open to modifying both of these behaviors, so if you want to PR these changes, we'll look at getting these merged in.

thanks!
