### ISSUE TITLE
JSONAPI compliance

### ISSUE THREAD

**Issue by mmartinson** [remiprev/her#340]
Is anyone working on tracking document structure changes in JSONAPI rc3 for the adapter? I'll need to get to work on this and don't want to to duplicate anyone's work if it's already underway.

**Comment by hubert** [comment]
hi mike. thanks for writing in.

i'm doing some work on adapting her to work with json api. i plan to open
an issue with README updates and perhaps some tests to make a proposal for
initial support in the next day or two. the upcoming spec is a big step
forward but has quite a lot in it, so help will certainly be welcome.

if you want to propose something straight away and kickstart the
discussion, go for it.

**Comment by hubert** [comment]
@mmartinson FYI #345
