### ISSUE TITLE
Is UPGRADE.md up to date with 0.7.x?

### ISSUE THREAD

**Issue by mpeteuil** [remiprev/her#348]
I noticed that [UPGRADE.md](https://github.com/remiprev/her/blob/master/UPGRADE.md) hasn't been updated in 2 years. Does that mean there haven't been any breaking changes since 0.6.x or has this document fallen out of date?

**Comment by hubert** [comment]
Hi @mpeteuil. Likely, it has fallen out of date. As a new maintainer, i don't have insight into the progress prior to 0.7. My plan is to change the scope of the document and to track all notable changes for releases moving forward. I will do this today.

I am following semver guidelines for this release and going forward, so there are not meant to be any breaking changes in this release.

**Comment by caomania** [comment]
Thank you. :+1:

**Comment by mpeteuil** [comment]
Sounds good, thanks @hubert
