### ISSUE TITLE
Parsing JSON API data fails

### ISSUE THREAD

**Issue by alexchumak** [remiprev/her#350]
Using active_model_serializers 0.10.0.rc2
Using her 0.7.6 from git://github.com/remiprev/her.git (at master)

Given this data from the API

    {
        data: [
            {
                id: "40d005a0-1aac-11e5-8fc3-4939c6dd88e9",
                type: "activities",
                attributes: {
                    ip: "xxx.xxx.254.90",
                    bot: true,
                    ...
                }
            },
            {
                id: "a5ccdd50-1aa9-11e5-8fc3-4939c6dd88e9",
                type: "activities",
                attributes: {
                    ip: "xxx.xxx.106.162",
                    bot: true,
                    ...
                }
            },
            ...
        ]
    }

Her fails to parse it. With the following error: "no implicit conversion of Symbol into Integer"

Line: .rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/her-0541bd44ee08/lib/her/model/parse.rb:173:in `[]'

Looks like Her is expecting `request_data[:data][:activities]` but AMS sends `request_data[:data]` as an array.

Am I mismatching versions? I tried AMS 0.8.3 but it doesn't seem to have JSON API support.

Please help.

**Comment by hubert** [comment]
@alexchumak you could try what's in master now. it has the first makings of jsonapi support (no relationships, included, etc.) so if your api is simple, that might work for you. 

i'm not sure about AMS support moving forward since the scope of AMS is changing quite a bit and given that, there won't be a strict definition of what "AMS format" is.

**Comment by alexchumak** [comment]
Seems to be working now! I was at master with the initial json api implementation and was getting that error. One of the consequent commits must've fixed it!

Thanks!

**Comment by alexchumak** [comment]
Actually, my bad @hubert, i was still running a cached copy of master that had my modification.

From the JSON API spec:

>Primary data MUST be either:
>
>- a single resource object, a single resource identifier object, or null, for requests that target single resources
>- an array of resource objects, an array of resource identifier objects, or an empty array ([]), for requests that target resource collections

The code in model/parse.rb assumes that there's a pluralized root node inside of data which doesnt seem to agree with the spec.

```ruby
def extract_array(request_data)
  if active_model_serializers_format? || json_api_format?
    request_data[:data][pluralized_parsed_root_element]
  else
    request_data[:data]
  end
end
```

For it to work, it should be returning only the `request_data[:data]` bit. Or am I misunderstanding something?

**Comment by hubert** [comment]
@alexchumak does your code follow this for consuming the json api compliant services?
https://github.com/remiprev/her#json-api-support

**Comment by alexchumak** [comment]
One of your recent commits fixed this issue. I'm able to use the master branch without any modifications now.

Probably this line:
https://github.com/remiprev/her/commit/8a5b80da597614160e9404c16ecb4a2d28923cf7#diff-9f46c6432f36a5642681207c26cf15f8R172
