### ISSUE TITLE
Module.synchronize deprecation and exception due #338

### ISSUE THREAD

**Issue by luislavena** [remiprev/her#357]
Hello,

First would like to thank for sharing Her!

Seems that after the changes introduced in #338, Her `master` no longer works with Rails 3.2.x, as it triggers the following exception on normal usage:

```ruby
class User
  include Her::Model
end

User.new
# ArgumentError: Synchronization needs a mutex. Supply an options hash with a :with key as the last argument (e.g. synchronize :hello, :with => :@mutex).
```

Which is being trigger from `lib/her/model/attributes.rb:222`

https://github.com/remiprev/her/blob/master/lib/her/model/attributes.rb#L222

The problem seems `generated_attribute_methods` does respond to `synchronize`, yet not the way is being expected.

Considering `Module#synchronize` being deprecated, perhaps define `Mutex` directly will be the alternative?

Thank you for your time.

**Comment by marshall-lee** [comment]
Hello! Thank you for your issue.
It was unable to reproduce on CI since Her does not automatically require all the ActiveSupport's quirks.

> perhaps define Mutex directly will be the alternative?

Her tries to create mutex directly only if it's necessary. Modern ActiveModel creates this mutex itself so we can reuse it.

**Comment by luislavena** [comment]
@marshall-lee thank you for your promptly response. Indeed #358 corrects this issue when loading it under a real Rails app.

Looking forward this gets merged :smile: 

Thank you :heart: :heart: :heart:
