### ISSUE TITLE
uninitialized constant Her::Middleware::JsonApiParser (NameError)

### ISSUE THREAD

**Issue by chadwtaylor** [remiprev/her#361]
I followed the README and included the provided JSON API implementation in `config/initializers/her.rb` and then running the server resulted in: `uninitialized constant Her::Middleware::JsonApiParser (NameError)`

I'm using `her 0.7.4`, `rails 4.2.1` and `ruby 2.2.2`.

**Comment by hubert** [comment]
hi @chadwtaylor 

the json api stuff got merged in after the 0.7.4 release. could you try updating to latest (0.7.6) and see if that solves your issue?

**Comment by chadwtaylor** [comment]
Upgraded to 0.7.6 and keeping it at rails 4.2.1 and ruby 2.2.1 still threw the same error:

```
/Users/chadwtaylor/Dropbox/web_projects/honey/waxapp/config/initializers/her.rb:18:in `block in <top (required)>': uninitialized constant Her::Middleware::JsonApiParser (NameError)
	from /Users/chadwtaylor/.gem/ruby/2.2.2/gems/her-0.7.6/lib/her/api.rb:78:in `block in setup'
	from /Users/chadwtaylor/.gem/ruby/2.2.2/gems/faraday-0.9.1/lib/faraday/connection.rb:91:in `initialize'
	from /Users/chadwtaylor/.gem/ruby/2.2.2/gems/faraday-0.9.1/lib/faraday.rb:70:in `new'
	from /Users/chadwtaylor/.gem/ruby/2.2.2/gems/faraday-0.9.1/lib/faraday.rb:70:in `new'
	from /Users/chadwtaylor/.gem/ruby/2.2.2/gems/her-0.7.6/lib/her/api.rb:77:in `setup'
	from /Users/chadwtaylor/.gem/ruby/2.2.2/gems/her-0.7.6/lib/her/api.rb:29:in `initialize'
	from /Users/chadwtaylor/.gem/ruby/2.2.2/gems/her-0.7.6/lib/her/api.rb:13:in `new'
	from /Users/chadwtaylor/.gem/ruby/2.2.2/gems/her-0.7.6/lib/her/api.rb:13:in `setup'
	from /Users/chadwtaylor/Dropbox/web_projects/honey/waxapp/config/initializers/her.rb:1:in `<top (required)>'```

**Comment by hubert** [comment]
can you paste the code in your initializer that is triggering the error?

**Comment by chadwtaylor** [comment]
```
Her::API.setup url: "http://localhost:3001" do |c|

  # Request (JSON API)
  c.use FaradayMiddleware::EncodeJson

  # Response
  c.use Her::Middleware::JsonApiParser

  # Adapter
  c.use Faraday::Adapter::NetHttp

end
```

**Comment by hubert** [comment]
doh. misread the commits. i merged this in after 0.7.6 so if you point your
Gemfile to the master branch on github, this should be fixed.

i'll be cutting a new release soon, so after that you should be able to use
the latest from rubygems.

thanks!

**Comment by chadwtaylor** [comment]
`gem 'her', :git => 'git://github.com/remiprev/her.git'` worked, thanks!

I really appreciate your prompt response to this issue.

**Comment by adamgotterer** [comment]
Having the same issue and was curious when you expected to cut 0.7.7? Thanks!

**Comment by hubert** [comment]
never :smirk:

but i'm cutting a 0.8.0 version now :smile:
