### ISSUE TITLE
NoMethodError inconsistent on attributes

### ISSUE THREAD

**Issue by 7h3kk1d** [remiprev/her#365]
``` ruby
f = Foo.new
f.bar
```

Throws NoMethodError

but...

``` ruby
Foo.new bar: 'bar'
f = Foo.new
f.bar
```

Returns nil

**Comment by hubert** [comment]
agree it is a bit surprising. is this something you stumbled across or was this at the root cause of an issue you were troubleshooting?

**Comment by 7h3kk1d** [comment]
It was an issue when testing. It could have been a problem in production though. Basically we were assuming the method would work because in test data it was.

**Comment by zacharywelch** [comment]
Gonna close due to inactivity. Feel free to reopen if this is still an issue.
