### ISSUE TITLE
Retrieve Api current user through `/me`

### ISSUE THREAD

**Issue by softmonkeyjapan** [remiprev/her#366]
My OAuth Api provider has a `/me` resource allowing to retrieve current user info using an access token. How can I achieve to connect to `/me` using Her? So far this is what I've done but it does not seems to work : 

```ruby
class Me
  include Her::Model
  collection_path '/me'
end
```

```ruby
module Her
  module Middleware
    class OAuthProviderHeader < Faraday::Middleware
      def add_header(headers)
        headers.merge! 'Content-Type' => 'application/json'
        headers.merge! 'Accept' => 'application/vnd.nemesis+json; version=1'
        headers.merge! 'Authorization' => "Bearer #{RequestStore.store[:access_token]}"
      end

      def call(env)
        add_header(env[:request_headers])
        @app.call(env)
      end
    end
  end
end
```
When calling `Me.all`, Her returns `#<Her::Model::Relation:0x007ff97e38c668 @parent=Me, @params={}, @_fetch=nil>`.

**Comment by hubert** [comment]
does the solution here work for you?

https://github.com/remiprev/her/issues/222

**Comment by softmonkeyjapan** [comment]
Thanks, it does works :)
