### ISSUE TITLE
ResourceInvalid is trying to join response_error which is a hash, and this raise an error when using save!

### ISSUE THREAD

**Issue by chentianwen** [remiprev/her#370]
This is the line that will raise error when using `save!`:
https://github.com/remiprev/her/blob/master/lib/her/errors.rb#L22

And the error, which is caused by `response_errors.join(", ")`, is:
```
NoMethodError: undefined method `join' for <#Hash...>
```

**Comment by hubert** [comment]
the response_errors should be an array, not a hash. if the api you are consuming with her is returning errors as a hash, you'll need to write custom parser that can translates that into the array that her is expecting.
