### ISSUE TITLE
Can't reload data association

### ISSUE THREAD

**Issue by mustela** [remiprev/her#375]
I have the following models and associations:

```
class Project < Entity
  has_many :devices
end 

class Device < Entity
  has_one :project
end

```

When I run 

```
Project.all.each do |project|
  project.devices.each { |device| device.hostname }
end
```

It fetches the projects, but since the API returns something like 

```
{
  "id": "xxx",
  "name": "project name",
  "devices": [{"href": "zzz", {"href:"yyyyy}]
}
```

When I try to access to `device.hostname` it fails because the association was already loaded with only the `href` attribute. And it seems I don't have a way to load the entire resource again.

I've seen this [PR](https://github.com/remiprev/her/pull/367) which could help, but wondering if there is an existing way of dealing with it.

Maybe disabling the cache?

Thanks

**Comment by zacharywelch** [comment]
Fixed in #367
