### ISSUE TITLE
Is it possible to PUT/POST application/json instead of application/x-www-form-urlencoded?

### ISSUE THREAD

**Issue by glappen** [remiprev/her#376]
Hello,

I am setting up Her for a project.  So far, I have my custom middleware working and can get members and collections form our API.  When I update a model and call save on it though, it does a PUT, and in the logs I see the MIME type is application/x-www-form-urlencoded.  Is it possible to send JSON instead?

Thanks!

**Comment by hubert** [comment]
hi greg. you can use any faraday middleware with her. so in your case,
something like this should work

```
Her::API.setup url: 'https://api.foo.com' do |c|
  c.request :json

  # rest of your setup goes here.
end
```
