### ISSUE TITLE
Single resource as array

### ISSUE THREAD

**Issue by Coolnesss** [remiprev/her#391]
Hey,

I'm trying to consume an API that looks something like this:

`GET /animals.json` => `"[{id:1, name:"Bear"}, {id:2, name:"Rat"}]`
`GET /animals/1.json` => `[{id:1, name:"Bear"}]`

As you can see, the single resource GET also returns an array with just the single element. This breaks Her, as it's expecting a hash. It throws: 
```ruby
NoMethodError: undefined method `keys' for []:Array
```

I'm trying to get past this by using a custom JSON parser, but I can't seem to figure out how to get rid of the top-level array. That's pretty much all i want to do with the custom parser: remove the array and let the default parse the rest.

Any help would be appreciated, thanks.

**Comment by singjsong** [comment]
Was looking through the issues, and while I don't have your exact problem, I know what would solve this. You do indeed need a custom parser.

 In `her.rb`, in the `Her::API.setup` block you would add something e.g.
```ruby
...
c.use MyCustomParser
...
```

And then in `my_custom_parser.rb`:
```ruby
class MyCustomParser < Faraday::Response::Middleware
  def on_complete(env)
    json = env[:body].is_a?(Hash) ? env[:body] : MultiJson.load(env[:body], symbolize_keys: true)

    # assuming your response body looks like "[{id:1, name:"Bear"}]"
    unrooted_resource = json.first
  end
end
```

Not exact, but that's the gist. Let me know if you have other questions.

**Comment by Coolnesss** [comment]
Hey, thanks for your answer. I already switched to another library for my project so I can't really test this anymore. I guess we can close the issue if that solves the problem :)
