### ISSUE TITLE
Activesupport >= 4.3.0

### ISSUE THREAD

**Issue by rafaelgonzalez** [remiprev/her#392]
Hello & happy new year!

[Rails v5.0.0.beta1](https://github.com/rails/rails/releases/tag/v5.0.0.beta1) was released a couple of weeks ago, and we are planning on upgrading one of our apps that uses Her to Rails 5.

Rails 5 requires activesupport v5.0.0.beta1 and Her currently supports it up to 4.2.0.

Now, I see there are specific Gemfiles for each version of activemodel, so I can make a PR with `her/gemfiles/Gemfile.activemodel-5.0.0.beta1` if you are down for supporting a beta version, or maybe `her/gemfiles/Gemfile.activemodel-5.0.x` ?

Let me know your thoughts.

Cheers

**Comment by djpate** [comment]
+1

**Comment by oliverzeyen** [comment]
:+1:

**Comment by bronson** [comment]
Yup, it's time!

**Comment by mokus80** [comment]
+1

**Comment by tokhi** [comment]
Even beta3 is out now.

**Comment by leighmackay-catapult** [comment]
+1

**Comment by rafaelgonzalez** [comment]
Let's all support #399 !

**Comment by johan-smits** [comment]
+1

**Comment by edtjones** [comment]
Hi folks,

I've just taken over maintenance of this gem and pushed 0.8.2 which includes support for Rails 5.
