### ISSUE TITLE
Jsonapi relationships

### ISSUE THREAD

**Issue by mehmetdavut** [remiprev/her#417]
I have an api project, serves JSON api with active_model_serializers' default jsonapi parser.
And I have an web client project which consumes jsonapi with Her models from api project.

Everything setted as written on documentation, but i can not get "relationships" object in jsonapi.

**Comment by mehmetdavut** [comment]
If i include Her::JsonApi::Model, i can not receive relationships data from my json

**Comment by edtjones** [comment]
Hi Mehmet

So is this a bug in the JSONAPI parser do you think? Are you including the relations in your responses?

(This is not a part of the codebase I know well)

Ed

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by mehmetdavut** [comment]
data.attributes includes relationships data from server response, but Her JsonApi parser excludes it from data, so it is not possible to reach these values. i made a change on parser and use on my project, so shared fix with pull request, if it is ok with your jsonapi parser: #418 

I think my models should reach to relationships data if server response contains it.
