### ISSUE TITLE
Calling `save` on an existing resource attempts to POST to and create new resource

### ISSUE THREAD

**Issue by ianks** [remiprev/her#421]
## Setup

```ruby
Her::API.setup url: 'https://api-endpoint.com/api/v2' do |c|
  # Request
  c.use Auth0Authorization
  c.use FaradayMiddleware::EncodeJson

  # Response
  c.use Faraday::Response::Logger, ActiveSupport::Logger.new(STDOUT) if Rails.env.development?
  c.use Her::Middleware::DefaultParseJSON

  # Adapter
  c.use Faraday::Adapter::NetHttp
end
```

```ruby
class User
  include Her::Model
end
```

## Bug in action

Here is a pry session (with some sensitive info cleaned up)

```
[3] pry(main)> u = User.find('auth0|56e843ce9e61a7af469f8020')
=> #<User(users) nickname='something' >
[5] pry(main)> u.nickname = 'test'
=> "test"
[6] pry(main)> u.save
post https://api-endpoint.com/api/v2/users
User-Agent: "Faraday v0.10.0"
Authorization: "Bearer <BEARER_TOKEN>"
Content-Type: "application/json"
400
date: "Wed, 23 Nov 2016 19:40:41 GMT"
content-type: "application/json; charset=utf-8"
transfer-encoding: "chunked"
connection: "close"
vary: "origin,accept-encoding"
cache-control: "no-cache"
=> false
````

## Discussion

As you can see, it attempts to create a new resource as opposed to creating a new one. I would expect this example to `PATCH https://api-endpoint.com/api/v2/users/:user_id` instead.

## Env

```
Gem version: v0.8.2
Rails: 5.0.0.1
Ruby: 2.3.1p112
```

**Comment by edtjones** [comment]
Thanks for a super bug report, Ian. I haven't seen something like this before. 

Does your user object have an id? Have you specified a different field to be the primary key? Does your user respond to new?() ?

Ed

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by ianks** [comment]
> Does your user object have an id?

It does not. What is the best way to configure this?

**Comment by edtjones** [comment]
that'll probably be it then :-) Something without an ID is considered new, I think. Can you return one in your result? If not, is there a primary key you can use as a substitute? You can configure your her-backed model to use that: https://github.com/remiprev/her#custom-primary-keys

**Comment by zacharywelch** [comment]
Closing this since her depends on an Id or primary key to be defined.
