### ISSUE TITLE
http raw response

### ISSUE THREAD

**Issue by nicolas-besnard** [remiprev/her#426]
Sometimes it could be nice to have access to the server raw response. Is it possible at this time ?

**Comment by edtjones** [comment]
Hi Nicolas

You could write a very small Faraday middleware to do that. I have done something similar which dumps env into stdout. 

Will dig out some code when I'm at my machine. 

Ed

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by zacharywelch** [comment]
Faraday includes a logger to `STDOUT`. Try giving this a shot :)

```ruby
Her::API.setup url: "https://api.example.com" do |c|
  # ...
  c.response :logger
end
```
