### ISSUE TITLE
Using scopes/"where" without API support

### ISSUE THREAD

**Issue by allthesignals** [remiprev/her#430]
Is it possible to use default scopes/scopes/`#where` when the API doesn't support those filter query params? 

For example, I think this generates `synchronizations?connector_type=arcgis`:

```
  default_scope {
     where(connector_type: 'arcgis')
  }
```

What would be an elegant way to apply the filter locally when API support is limited? 

Thank you!

**Comment by edtjones** [comment]
Hi @allthesignals - are you trying to hit the api with a different parameter, or do you want to stop hitting the api at all under these circumstances?

**Comment by allthesignals** [comment]
Hi @edtjones - thanks for the response.  I want to hit the API as if it were a regular 'User.all', but then filter using #where or apply a scope. So, this would create GET '/users', get all the data, and apply a default 'where' scope or filter _in memory_ as if it were some array of hashes. Right now 'where' generates the request 'users?column=value' but since the API doesn't filter at all, it returns the whole unfiltered collection. 

(Also, thanks for picking up this project, it's fantastic)

**Comment by edtjones** [comment]
hi @allthesignals 

Well: really you don't want to involve Her at all for that, by the sound of it. I've used a pattern in the past for filtering posts returned from our headless WordPress, https://www.rooftopcms.com - get all your objects once, then filter them in memory using Enumerable#select and union the collections.

Here's a snippet of code which filters a collection of events. In this case there are scopes on Event called things like `showing_between`, which actually do make requests to the API. This particular example is in a controller but you could refactor this code to be a class method on an API-backed model.

```
def filter_events(events)

    # What we're going to do is push into this array a bunch of different collections which match different filter criteria. At the end, anything which is in the results of all the filters will be the matching selection we want, so we can just union them.
    # So say we have [[a,b,c],[a,c],[b,c]], only c will match all 3 filters and be returned when 
    # we call (:&) on the array.

    # Build a collection of collections, which we will intersect to get only ones which match all
    all_match = []

    # push into the array anything which matches the date criteria
    if params[:from].present? && params[:to].present?
      from = DateTime.parse(params[:from]) rescue DateTime.now
      to = DateTime.parse(params[:to]) rescue DateTime.now
      all_match << events.showing_between(from,to)
    elsif params[:from].present?
      from = DateTime.parse(params[:from]) rescue DateTime.now
      all_match << events.showing_on(from)
    end

    # Push into the array anything which matches the venue
    if params[:venue].present?
      all_match << events.matching_summary_venue(params[:venue])
    end

    # Push into the array anything which matches the genre
    if params[:genre].present?
      all_match << events.with_genre(params[:genre])
    end

    # free-text search
    if params[:q].present?
      all_match << events.matching_query(params[:q])
    end

    # intersect all collections to return only the ones which match all the filters
    all_match.inject(:&)

  end
```

Hope this might help? I was mulling suggesting you reimplement `scope()` in your class with Her::Model mixed in but I think you could easily get in a muddle. If you want to do this in a model class, I'd decide on another class method name.

**Comment by allthesignals** [comment]
@edtjones, thank you for the thoughtful response - I think my issue had more to do with developer ergonomics - I can work around this, but when "#where" doesn't actually filter anything (silently failing), it can present some gotchas to other developers. Not really a huge deal. 

This helps quite a lot, thank you - basically, you're recreating in-memory filters which allows params to be used by the client.

**Comment by edtjones** [comment]
Cool - glad it helped. I will close this issue but if you want to submit a PR with a way to do what you want and it's generic enough, we can certainly discuss merging it.
