### ISSUE TITLE
URL parameter special characters

### ISSUE THREAD

**Issue by stephen-kainos** [remiprev/her#432]
I've got a need to use a URL GET parameter called _embed with Her. When this is added using the where method it appears to get stripped from the actual request. 

The same request works successfully with standalone Faraday. Does Her have a restriction on parameter names?

**Comment by edtjones** [comment]
Hi @stephen-kainos sounds like you're connecting to WordPress :-) The answer is that underscored parameters are stripped - I'm afraid I can't remember why / where.

We solved this in our Rooftop CMS Ruby client, which uses Her. The answer is you have to mangle the request in a Faraday middleware.

Here's how we did it:

https://github.com/rooftopcms/rooftop-ruby/blob/master/lib/rooftop/middleware/embed_middleware.rb#L10

(You use is like this: `where(include_embedded_resources: true)`)

HOWEVER: Rooftop CMS is WordPress with a bunch of plugins to make the API more useful - you might well find you can use the rooftop-ruby gem as-is: https://github.com/rooftopcms/rooftop-ruby

(Would also recommend checking out Rooftop in its entirety if you are using WordPress - it's open source: https://www.rooftopcms.com/)
