### ISSUE TITLE
Need to call `nil?` on associated object to be able to evaluate presence of that object.

### ISSUE THREAD

**Issue by bytnar** [remiprev/her#434]
### Example:
`:ok if MyModel.find('X').related_object.nil? => :ok`
`:ok if MyModel.find('X').related_object => :ok` - also if ok ?!?

`MyModel.find('X').related_object => nil`

### Description:
By default MyModel.find('X').related_object returns proxy object (which is not nil result)
It is required to call nil? to get proper object for using `unless` construction

**Comment by zacharywelch** [comment]
`find` is one of the few methods which terminates the proxy and issues a `fetch`.  Is `related_object` an attribute on your model or another association? If you could put a snippet or gist together that'd be a huge help 😺

**Comment by zacharywelch** [comment]
Going to close this due to inactivity. Feel free to reopen if it's still a problem and you have more information.
