### ISSUE TITLE
Dash in resource name

### ISSUE THREAD

**Issue by mkarganov** [remiprev/her#438]
Hi, is it possible to define a has_one association with a dash inside name? Smth like the following:
```
class User
  include Her::Model
  has_one :profile_data
end

class ProfileData
  include Her::Model
  resource_path: 'profile-data'
end
```
What I want to archive is: 
`@user.profile_data` should make a call to
`/users/:id/profile-data` instead of `/users/:id/profile_data`.

If I try now without the line `resource_path: 'profile-data'` no call is done but result is:
(Object doesn't support #inspect)
 =>

**Comment by edtjones** [comment]
Strange. Should certainly be possible. Although I think your resource path is wrong - I assume it's /profile-data/:id ? Or maybe /users/:user_id/profile-data/:id ?

Note that the profile data response needs to have a key called user_id with the user's id if you want to be able to call the user from the profile object. 


Can you proxy the request so we can see what's happening? Are you sure there's no request being made?


--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by mkarganov** [comment]
Hi **edtjones**, thank you for fast response.

Yes, you are right, maybe missing id for profile-data/:id is the cause, unfortunately I am not the guy who designs API, just consuming it. And the endpoint just looks like /users/:user_id/profile-data (without any id for it). 

So most likely I have to use `custom_get` to get the data. Or there are other ways?

P.S. I am logging all requests and while trying with this one I do not see any logs.

**Comment by edtjones** [comment]
Not near a machine to have a play around but a profile() method on user which does a custom get wouldn't be a bad way to do this. 

--
Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by mkarganov** [comment]
Great, thnx!
