### ISSUE TITLE
Devise with Her ORM

### ISSUE THREAD

**Issue by myxrome** [remiprev/her#446]
Does anyone run Devise (https://github.com/plataformatec/devise) with Her ORM? Devise require orm_adapter based on https://github.com/ianwhite/orm_adapter. I've tried to found it for Her ORM, but have no luck. It would be very helpfull if someone can share successful experience.

Thanks!

**Comment by edtjones** [comment]
Hi @myxrome - interesting idea! Devise has a LOT of hooks into the database. I haven't reviewed the ORM adaptor - would be an interesting exercise - but it feels like it might be hard work to make everything work as devise expects. 

Maybe I'm being overly pessimistic though 🙂

**Comment by myxrome** [comment]
I've created my own ORM Adapter for Her ORM [orm_adapter-her](https://github.com/myxrome/orm_adapter-her) and it's worked for me. Now I can use Devise based on Her ORM.
