### ISSUE TITLE
Ready for a gem build?

### ISSUE THREAD

**Issue by edtjones** [remiprev/her#448]
@zacharywelch are you ready for me to do a gem build? or is there more you'd like to merge first?

**Comment by zacharywelch** [comment]
Wanna merge #367 first and get all the `reload` goodies in one build? That should also let us close out #440 😄

**Comment by edtjones** [comment]
👍 we probably have some readme work to do too.

**Comment by stereobooster** [comment]
can you please merger this one https://github.com/remiprev/her/pull/449 before release. Thanks

**Comment by zacharywelch** [comment]
released 0.9.0 w/ [release notes](https://github.com/remiprev/her/releases/tag/v0.9.0) 👍

**Comment by shashiprab** [comment]
Thanks Zachary! Wonderful to see the progress on Her gem. 

-Shashi
