### ISSUE TITLE
save methods with arguments.

### ISSUE THREAD

**Issue by myxrome** [remiprev/her#458]
[Devise](https://github.com/plataformatec/devise) call save(validate: false) for model object to save object without validation, but Her doesn't support any arguments in save methods and doesn't support validation skip at all. 
Could you please add add skip validation functionality to save method (like ActiveRecord do) or simply add any arguments to save method definition (like save(*))?

**Comment by jkappers** [comment]
Her doesn't validate when you call `save`, so validation is essentially always "skipped". You have to explicitly call the `validate` method.

```ruby
model.save if model.valid?
```

One solution for this specific case is to override the save method on your model.

```ruby
class User
  include Her::Model
  
  def save(options = nil)
    super()
  end
end
```
