### ISSUE TITLE
`where` merges instead of deep_merges

### ISSUE THREAD

**Issue by jkappers** [remiprev/her#459]
```ruby
scope = User
  .where(filter: { a: 1 })
  .where(filter: { b: 2 })

scope.params # { filter: { b: 2 }
```
I was expecting `scope.params` it to be: `{ filter: { a: 1, b: 2 } }`.

Updating the relation to do a deep_merge would resolve this, but may result in breaking changes for those who have expected an overwrite instead of a merge.

What direction would you prefer?

**Comment by jkappers** [comment]
In case anyone else runs into this issue, this is how I'm getting around it.

Exercise caution: `blank_relation` is a private method.

```ruby
# Added to config/initializers/her.rb
module Her
  module Model
    class DeepMergeRelation < Relation
      def where(params = {})
        return self if params.blank? && !@_fetch.nil?
        self.clone.tap do |r|
          r.params = r.params.deep_merge(params) # This is the only difference from `Relation`.
          r.clear_fetch_cache!
        end
      end
    end
  end
end

 # Override the `blank_relation` class method in your model so that it returns this new relation.
 class User < ResourceBase
   def self.blank_relation
     @blank_relation ||= DeepMergeRelation.new(self)
   end
 end
```

**Comment by zacharywelch** [comment]
Hi Joshua,

Sorry for taking so long to respond. Don't really have a strong opinion on this and see how appending filters in the example above would be useful. Of course there's also the option of passing them in a single where clause.

```ruby
scope = User.where(filter: { a: 1, b: 2 })
```

For their part, `ActiveResource` uses a `merge` while `ActiveRecord` appends where clauses. That said `deep_merge` was added in activesupport 3.0 so if we wanted to change this behavior we at least don't need to update any dependencies 😅

**Comment by jkappers** [comment]
No problem!

I have some code that chains where clauses, but your idea to combine the parameters first wasn't something I had considered. I'm going to see what it would take to update my code to do that instead because it would be a lot cleaner and way easier to test! Nice idea!

**Comment by zacharywelch** [comment]
Glad it helped. Good luck 😃
