### ISSUE TITLE
Add middleware for parsing HAL & Collection+JSON?

### ISSUE THREAD

**Issue by mattiassvedhem** [remiprev/her#48]
Would it be a good idea to include parsers for hypermedia types?

**Comment by ekampp** [comment]
@remiprev I'm in the position that I'd love to use Her for a project. The backend delivers HAL JSON, so I need to develop a middleware to parse the JSON. 

HAL formats the JSON like this:

```json
{
  "_embedded": {
    "users": [
      {
        "id": 1,
        ...
      },
      ...
    ]
  }
```

Can you guide me to where in the Her project I should map the name of the class calling the endpoint, and the nesting in the JSON? 

Thanks in advance.

**Comment by AwakenTheJaken** [comment]
I hate to dig up an old thread, but in my search for a solution to this I stumbled across it and I wanted to share what I learned. What I did was create a Faraday Response Middleware and parse the data like this:
```
class Akeneo::Parser < Faraday::Response::Middleware
  def on_complete(env)
    json = MultiJson.load(env[:body])
    if json['_links'].blank?
      env[:body] = {
        data: json,
        errors: json[:errors]
      }
    else
      env[:body] = {
        data: json['_embedded']['items'],
        errors: json[:errors],
        metadata: json['_links']
      }
    end
  end
end
```
It isn't the most robust solution, as it is only checking if the response contains `['_links']` but it works for my needs. I hope this will help someone else with a similar issue or even lead to a better solution!
