### ISSUE TITLE
Is it possible to use form_for with Her?

### ISSUE THREAD

**Issue by samstarling** [remiprev/her#482]
Hello. Is there a recommended way of using `form_for` with Her? If I just use it, then I get the following error: 

```
undefined method `foo_clients_path' for #<#<Class:0x007fadcfd0aed8>:0x007fadd04bdae0>
```

`Foo` is the name of my module with the Her models in (so I have `Foo::Client.new` in the controller. I guess this makes sense because it can't resolve the path, but if I pass in a `url` parameter to `form_for`, it then starts choking on the field names:

```
# This code
<%= form_for(@client, url: 'foo') do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Create" %>
<% end %>

# Gives this exception
undefined method `name' for #<Foo::Client(clients) >
```

Any advice on how to do this would be much appreciated - I saw on other issues that folks seem to successfully be using `form_for`, but maybe I missed something. Thanks!

**Comment by samstarling** [comment]
Hey @edtjones @zacharywelch – sorry to ping you directly, but I wondered if you had any ideas here?

**Comment by samstarling** [comment]
@edtjones Ah OK – I'll have a play around, and if I find anything then I'll let you know, it'd be cool to add it to the documentation if there's a nice solution. I'll give it some thought.

**Comment by samstarling** [comment]
I'll close this, given it's a pretty vague question. If I learn or discover anything, I'll be sure to contribute back.

**Comment by edtjones** [comment]
Thanks @samstarling that sounds really helpful.

**Comment by zacharywelch** [comment]
Apologize for not getting back to you on this @samstarling. I went ahead and put together a [sample project](https://github.com/zacharywelch/her_sample_app) using `form_for`. Take a look and see if that helps. If not feel free to reopen the issue.

Thanks!

**Comment by samstarling** [comment]
@zacharywelch No need to apologise – this is really useful: I realised the main mistake I was making was that my models were not in the `models` folder, and now `_path` helper methods and so on work much better – `form_for` was having problems there, because everything was in the `lib` directory, so that's my mistake.

One other question – I can't seem to get model validations working. For example, I have a model with a simple `validates :name, presence: true` – but when I call `User.new().save`, it doesn't have anything in it's `errors` object. Is there something I missed?

**Comment by samstarling** [comment]
Ah, wait – this is (again!) my fault, that validations are not run. There is a problem when I call `@model.valid?` which results in an exception with the following (truncated) stack trace:

```
ArgumentError in AccountsController#create: wrong number of arguments (given 2, expected 1)

her (0.10.0) lib/her/model/attributes.rb:142:in `attribute?'
activemodel (5.1.4) lib/active_model/attribute_methods.rb:384:in `attribute_changed_in_place?'
her (0.10.0) lib/her/model/attributes.rb:50:in `method_missing'
activemodel (5.1.4) lib/active_model/attribute_methods.rb:429:in `method_missing'
activemodel (5.1.4) lib/active_model/validations/numericality.rb:102:in `record_attribute_changed_in_place?'
activemodel (5.1.4) lib/active_model/validations/numericality.rb:25:in `validate_each'
activemodel (5.1.4) lib/active_model/validator.rb:150:in `block in validate'
activemodel (5.1.4) lib/active_model/validator.rb:147:in `each'
activemodel (5.1.4) lib/active_model/validator.rb:147:in `validate'
activesupport (5.1.4) lib/active_support/callbacks.rb:413:in `block in make_lambda'
activesupport (5.1.4) lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
activesupport (5.1.4) lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
activesupport (5.1.4) lib/active_support/callbacks.rb:600:in `catch'
...
```

I don't think there is anything special about my model or my controller, but let me know if you'd like any additional information.

**Comment by zacharywelch** [comment]
#382 documents the issue w/ `validates_numericality_of`. There's an open [PR](https://github.com/remiprev/her/pull/383) that seems to fix the issue but need to take another look and see if we can update ActiveModel instead. Until then hope this helps.

Thanks!
