### ISSUE TITLE
Rails 5.2.0 support

### ISSUE THREAD

**Issue by siim2812** [remiprev/her#487]
I tried to run her against rails-5.2.0.rc1 and I see a lot of test failures. Most of them are related to activemodel-dirty and attributes API. My question is are you planning to add rails-5.2.0 support?

**Comment by martinstreicher** [comment]
:+1: here.

**Comment by edtjones** [comment]
@martinstreicher @siim2812  yes we're planning to sort this out imminently. @zoltankiss is planning on leading this ticket. PRs welcome :)

**Comment by martinstreicher** [comment]
Happy to test a PR when it is ready. We are using JSONAPI.

**Comment by zoltankiss** [comment]
here is what I have so far, take a look https://github.com/remiprev/her/pull/492

It works well against 5.2, 5.1, 5.0, 4.2, 3.2. I've waited this long to open the PR since there's still some stuff I'm undecided about and may want to rework before the final version.

**Comment by edtjones** [comment]
Looks excellent @zoltankiss - thanks heaps for your work on it. What’s still undecided in your mind? Is it the underscore variable name for @_attributes? I can’t think of a better name to be honest. Is it ready for @martinstreicher to have a play with?

Thanks again - really great to have your help.

**Comment by martinstreicher** [comment]
Let me know if there is a commit to point to and we can run our specs.

**Comment by zacharywelch** [comment]
Rails 5.2 support is now available in [v1.0.0](https://github.com/remiprev/her/releases/tag/v1.0.0) 🎉  
Thanks!
