### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by voltechs** [remiprev/her#504]
As an open source maintainer myself, I understand keeping a changeling up-to-date can be a chore, but as even more of an open source consumer how invaluable they are.

With 1.x in progress (and 1.0.1 releases as of writing this), a Changelog would be so helpful!

**Comment by zacharywelch** [comment]
We’ve been happy so far with github releases to maintain a changelog. Thanks!

**Comment by voltechs** [comment]
That’s unfortunate. Thanks for the consideration. Best of luck, and thanks for the gem.
