### ISSUE TITLE
Belongs_to options are not used when building request

### ISSUE THREAD

**Issue by seanbjornsson** [remiprev/her#506]
I did some digging and could be mistaken, but it seems to me that the path option in the belongs_to association method should override the path that the association is found at. 
The line that builds the path is found [here](https://github.com/remiprev/her/blob/master/lib/her/model/associations/belongs_to_association.rb#L83), but does not seem to use the path option in any way [here](https://github.com/remiprev/her/blob/master/lib/her/model/associations/belongs_to_association.rb#L14). 

I am attempting to set up an association as follows:
```ruby
belongs_to :something, 
  foreign_key: 'something_internal_symbol', 
  path: 'something/is/:internal_symbol', 
  primary_key: 'internal_symbol'
```

but the path that is requested is always something/:id, which is of course that object's primary key.
This is because the path is built by asking the association class, without first checking if the path option is set. 

Do folks agree that should be checked first?

Additionally, other options, such as the primary key specification, are also not used when building request params. 

Perhaps I am misunderstanding the usage of the options upon setup?

**Comment by zacharywelch** [comment]
You're correct @seanbjornsson. The `path` option for associations should override any defaults, including [belongs_to](https://www.rubydoc.info/github/remiprev/her/Her%2FModel%2FAssociations%2FClassMethods:belongs_to) associations. This appears to be an issue in each of the association types. Working on a fix but need to run through some tests first 😺
