### ISSUE TITLE
Support for update_attributes missing?

### ISSUE THREAD

**Issue by noctivityinc** [remiprev/her#521]
Maybe I'm missing something but I was surprised to find that the update_attributes method appears to either be missing or broken.  This is a pretty standard Rails method, so I assumed support.  Can someone tell me if there is another way I'm suppose to be doing this?

**Comment by zacharywelch** [comment]
Hi @noctivityinc, `update_attributes` was [deprecated](https://github.com/remiprev/her/blob/fd192875777f11135ec2188a4a9b8346226b9561/lib/her/model/deprecated_methods.rb#L26) in favor of `assign_attributes` long ago (see [usage](https://github.com/remiprev/her#activerecord-like-methods)). Not sure why this was done, but it shouldn't be difficult to add `update_attributes` and have it behave similar to ActiveRecord in that it calls `save` afterwards. I'll take a crack at it tomorrow 👍

**Comment by noctivityinc** [comment]
Thanks @zacharywelch but the issue with this is that, for some reason, it doesnt support *strong parameters.*  I get an ```undefined method `each_with_object' for #<ActionController::Parameters>```
message when trying to pass strong parameters to assign_attributes.

**Comment by noctivityinc** [comment]
Weird thing is that something like ```User.new(user_params)``` works fine where ```@user = User.assign_attributes(user_params)``` fails.

**Comment by noctivityinc** [comment]
For that matter - ```User.assign_attributes(params[:user])``` fails also, so I think assign_attributes is broken.  For now, I'm doing this:

```
    user_params.each do |x|
      @user.send("#{x}=",user_params[x])
    end
```

**Comment by zacharywelch** [comment]
`update_attributes` added in 1849339b317177e9dfc5546aa413be45b779c63f as well as [support](https://github.com/remiprev/her/commit/8a0d873fea29c1fe53ee47a71a04a5063c082b99) for strong parameters. Like ActiveRecord you'll need to permit these params before sending them to your Her model.

```ruby
user_params = params.permit(:name, :email)

# initialize with params
user = User.new(user_params)

# assign params
user.assign_attributes(user_params)

# update with params
user.update_attributes(user_params)
```

Gonna close this as fixed now 😺

**Comment by noctivityinc** [comment]
Thats excellent, thank you.
